BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Liste_des_Aérodromes_en_France" (
	"Département"	INTEGER,
	"Commune"	TEXT,
	"CodeOACI"	TEXT,
	"ALL"	INTEGER,
	"NORM"	INTEGER,
	"TR00"	INTEGER,
	"TR10"	INTEGER,
	"TR11"	INTEGER,
	"MM1L"	INTEGER,
	"LY10"	INTEGER
);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (1,'Château-Gaillard, Ambronay','LFXA',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (1,'Valserhône','LFHN',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (1,'Jasseron','LFHS',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (1,'Grand-Saconnex et Meyrin en Suisse','LSGG',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (1,'Arbent','LFLK',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (1,'Peyrieu','LFKY',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (1,'Corlier','LFJD',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (1,'Pérouges','LFHC',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (2,'Laon','LFAF',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (2,'Roupy','LFOW',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (2,'Château-Thierry','LFFH',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (2,'Saint-Simon','LFYT',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (2,'Courmelles','LFJS',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (3,'Lurcy-Lévis','LFJU',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (3,'Toulon-sur-Allier','LFHY',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (3,'Périgny','LFHX',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (3,'Domérat','LFLT',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (3,'Charmeil, Saint-Rémy-en-Rollat','LFLV',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (4,'Saint-Pons','LFMR',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (4,'Château-Arnoux-Saint-Auban','LFMX',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (4,'Puimoisson','LFTP',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (4,'Vaumeilh','LFNS',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (5,'Aspres-sur-Buëch','LFNJ',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (5,'Tallard','LFNA',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (5,'Saint-Crépin','LFNC',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (5,'La Bâtie-Montsaléon','LFTM',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (5,'Saint-Étienne-en-Dévoluy','LFNY',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (6,'Cannes','LFMD',1,1,NULL,1,1,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (6,'Nice','LFMN',1,1,NULL,1,1,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (6,'Juan-les-Pins',NULL,1,1,NULL,1,1,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (6,'Cannes',NULL,1,1,NULL,1,1,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (6,'Cannes','LFTL',1,1,NULL,1,1,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (7,'Lanas','LFHO',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (7,'Lespéron','LFHL',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (7,'Ruoms','LFHF',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (8,'Douzy','LFSJ',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (8,'Tournes, Belval','LFQV',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (8,'Sault-lès-Rethel','LFAP',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (9,'Lorp-Sentaraille','LFCG',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (9,'Les Pujols, Verniolle','LFDJ',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (10,'Barberey-Saint-Sulpice','LFQB',1,NULL,1,1,1,'',NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (10,'Saint-Christophe-Dodinicourt, Lassicourt','LFFN',1,NULL,1,1,1,'',NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (10,'Romilly-sur-Seine','LFQR',1,NULL,1,1,1,'',NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (10,'Bar-sur-Seine','LFFR',1,NULL,1,1,1,'',NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (10,'Juvancourt','LFQX',1,NULL,1,1,1,'',NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (11,'Carcassonne','LFMK',1,1,1,1,1,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (11,'Lézignan-Corbières','LFMZ',1,1,1,1,1,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (11,'Labécède-Lauragais','LFMG',1,1,1,1,1,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (11,'Narbonne','LFNN',1,1,1,1,1,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (11,'Villeneuve-la-Comptal, Mas-Saintes-Puelles','LFMW',1,1,1,1,1,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (11,'Moussoulens','LF34',1,1,1,1,1,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (11,'Puivert','LFNW',1,1,1,1,1,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (12,'Salles-la-Source','LFCR',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (12,'Belmont-sur-Rance','LFIF',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (12,'Cassagnes-Bégonhès','LFIG',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (12,'L''Hospitalet-du-Larzac','LFCM',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (12,'Villefranche-de-Rouergue','LFCV',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (13,'Aix-en-Provence','LFMA',1,1,1,1,1,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (13,'La Fare-les-Oliviers','LFNR',1,1,1,1,1,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (13,'Berre-l''Étang','LFTB',1,1,1,1,1,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (13,'Marignane','LFML',1,1,1,1,1,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (13,'Saint-Rémy-de-Provence','LFNZ',1,1,1,1,1,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (13,'Salon-de-Provence','LFNE',1,1,1,1,1,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (13,'Istres','LFMI',1,1,1,1,1,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (13,'Salon-de-Provence','LFMY',1,1,1,1,1,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (14,'Carpiquet','LFRK',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (14,'Saint-Gatien-des-Bois','LFRG',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (14,'Falaise','LFAS',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (14,'Condé-sur-Noireau','LFAN',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (15,'Aurillac','LFLW',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (15,'Coltines','LFHQ',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (16,'Châteaubernard','LFBG',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (16,'Champniers','LFBU',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (16,'Chalais','LFIH',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (17,'Saint-Germain-de-Lusignan','LFCJ',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (17,'Saint-Just-Luzac','LFJI',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (17,'Avy','LFCP',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (17,'Saint-Agnant','LFDN',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (17,'Soubise','LFXR',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (17,'La Rochelle','LFBH',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (17,'Médis','LFCY',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (17,'Thénac','LFXB',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (17,'Saint-Jean-d''Angély','LFIY',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (17,'Saint-Pierre-d''Oléron','LFDP',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (18,'Bourges','LFLD',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (18,'Aubigny-sur-Nère','LFEH',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (18,'Avord','LFOA',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (18,'Serruelles','LFFU',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (18,'Méreau','LFFV',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (19,'Brive-la-Gaillarde','LFBV',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (19,'Nespouls','LFSL',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (19,'Égletons','LFDE',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (19,'Saint-Exupéry-les-Roches','LFCU',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES ('2A','Ajaccio','LFKJ',1,1,'','','',1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES ('2A','Figari','LFKF',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES ('2A','Propriano','LFKO',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES ('2B','Ventiseri','LFKS',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES ('2B','Bastia','LFKB',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES ('2B','Calvi','LFKC',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES ('2B','Corte','LFKT',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES ('2B','Ghisonaccia','LFKG',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (21,'Beaune','LFGF',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (21,'Baigneux-les-Juifs','LFSY',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (21,'Châtillon-sur-Seine','LFQH',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (21,'Darois','LFGI',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (21,'Longvic','LFSD',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (21,'Nuits-Saint-Georges','LFGZ',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (21,'Maconge, Meilly-sur-Rouvres','LFEP',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (21,'Liernais','LFEW',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (21,'Semur-en-Auxois','LFGQ',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (21,'Til-Châtel','LFET',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (22,'Trélivan','LFEB',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (22,'Lannion','LFRO',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (22,'Trémuson','LFRT',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (22,'Saint-Brieuc','LFAZ',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (23,'Lépaud','LFBK',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (23,'Saint-Laurent','LFCE',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (24,'Bergerac','LFBE',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (24,'Condat-sur-Vézère','LFDZ',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (24,'Bassillac','LFBX',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (24,'Domme','LFDS',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (24,'Belvès','LFIB',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (24,'Ribérac','LFIK',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (24,'Fougueyrolles','LFDF',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (25,'La Vèze','LFQM',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (25,'Thise','LFSA',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (25,'Courcelles-lès-Montbéliard','LFSM',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (25,'Pontarlier','LFSP',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (25,'Valdahon','LFXH',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (26,'Saint-Paul-lès-Romans','LFHE',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (26,'Chabeuil','LFLU',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (26,'Pierrelatte','LFHD',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (26,'Saint-Rambert-d''Albon','LFLR',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (26,'Aubenasson','LFJF',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (26,'La Motte-Chalancon','LFJE',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (26,'Montélimar','LFLQ',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (26,'Saint-Jean-en-Royans','LFKE',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (27,'Les Authieux','LFFD',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (27,'Bernay','LFPD',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (27,'Étrépagny','LFFY',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (27,'Évreux','LFOE',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (28,'Bailleau-Armenonville','LFFL',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (28,'Champhol','LFOR',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (28,'Châteaudun','LFOC',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (28,'Vernouillet','LFON',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (29,'Morlaix','LFRU',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (29,'Guipavas','LFRB',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (29,'Pluguffan','LFRQ',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (29,'Landivisiau','LFRJ',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (29,'Lanvéoc','LFRL',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (29,'Ouessant','LFEC',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (30,'Pujaut','LFNT',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (30,'Deaux, Vézénobres','LFMS',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (30,'La Grand-Combe','LFTN',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (30,'Nîmes','LFME',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (30,'Garons','LFTW',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (30,'Uzès','LFNU',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (31,'Bagnères-de-Luchon','LFCB',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (31,'Palaminy','LFJH',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (31,'Cugnaux, Portet-sur-Garonne','LFBF',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (31,'Muret','LFBR',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (31,'Revel','LFIR',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (31,'Clarac','LFIM',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (31,'Blagnac','LFBO',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (31,'Bourg-Saint-Bernard','LFIT',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (31,'Balma','LFCL',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (31,'Toulouse','LFIO',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (31,'Sabonnères','LF3126',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (32,'Auch','LFDH',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (32,'Condom','LFID',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (32,'Nogaro','LFCN',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (33,'Andernos-les-Bains','LFCD',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (33,'La Teste-de-Buch','LFCH',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (33,'Léognan','LFCS',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (33,'Mérignac','LFBD',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (33,'Martignas-sur-Jalle','LFDO',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (33,'Yvrac','LFDY',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (33,'Les Artigues-de-Lussac','LFDI',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (33,'La Teste-de-Buch','LFBC',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (33,'Floudès','LFDR',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (33,'Saint-Laurent-Médoc','LFDU',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (33,'Marcillac','LFDC',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (33,'Soulac-sur-Mer','LFDK',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (33,'Vendays-Montalivet','LFIV',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (34,'Pérols, Mauguio','LFMT',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (34,'La Tour-sur-Orb','LFNX',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (34,'Portiragnes, Vias','LFMU',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (34,'Candillargues','LFNG',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (34,'Nizas','LFNP',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (34,'Saint-Martin-de-Londres','LFNL',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (35,'Pleurtuit','LFRD',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (35,'Saint-Jacques-de-la-Lande','LFRN',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (35,'Bains-sur-Oust','LFER',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (35,'Saint-Sulpice-des-Landes','LFSS',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (35,'Saint-Malo','LFEO',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (36,'Saint-Aubin','LFEK',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (36,'Argenton-sur-Creuse','LFEG',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (36,'Le Blanc','LFEL',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (36,'Saint-Maur','LFEJ',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (36,'Déols','LFLX',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (37,'Dierre','LFEF',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (37,'Sorigny','LFEN',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (37,'Le Louroux','LFJT',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (37,'Tours','LFOT',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (38,'Saint-Étienne-de-Saint-Geoirs','LFLS',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (38,'Le Versoud','LFLG',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (38,'Huez','LFHU',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (38,'Cessieu','LFKP',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (38,'Morestel','LFHI',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (38,'Saint-Jean-d''Avelanne','LFKH',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (38,'Reventin-Vaugris','LFHH',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (39,'Tavaux','LFGJ',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (39,'Arbois','LFGD',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (39,'Crotenay','LFGX',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (39,'Courlaoux','LFGL',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (39,'Pratz','LFKZ',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (40,'Biscarrosse','LFBS',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (40,'Aire-sur-l''Adour','LFDA',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (40,'Oeyreluy, Seyresse','LFBY',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (40,'Mimizan','LFCZ',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (40,'Mont-de-Marsan','LFBM',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (40,'Rion-des-Landes','LFIL',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (41,'Blois','LFOQ',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (41,'Pruniers-en-Sologne, Gièvres','LFYR',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (41,'Lamotte-Beuvron','LFFM',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (42,'Saint-Léger-sur-Roanne','LFLO',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (42,'Chambéon','LFLZ',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (42,'L''Horme','LFHG',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (42,'Saint-Étienne','LFMH',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (42,'Saint-Galmier','LFKM',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (43,'Beaumont','LFHR',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (43,'Loudes','LFHP',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (44,'Ancenis','LFFI',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (44,'La Baule-Escoublac','LFRE',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (44,'Bouguenais','LFRS',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (44,'Montoir-de-Bretagne','LFRZ',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (45,'Vimory','LFEM',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (45,'Saint-Denis-de-l''Hôtel','LFOZ',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (45,'Briare','LFEI',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (45,'Bricy','LFOJ',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (45,'Pithiviers','LFFP',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (46,'Cieurac','LFCC',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (46,'Durbans','LFCF',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (47,'Marmande','LFDM',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (47,'Agen','LFBA',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (47,'Montayral','LFDX',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (47,'Villeneuve-sur-Lot','LFCW',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (48,'Hures-la-Parade','LFNO',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (48,'Brenoux','LFNB',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (49,'Marcé','LFJR',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (49,'Cholet','LFOU',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (49,'Saumur','LFOD',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (49,'Pouancé','LFTQ',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (49,'Avrillé','LFRA',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (50,'Le Val-Saint-Père','LFRW',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (50,'Maupertus-sur-Mer, Gonneville','LFRC',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (50,'Bréville-sur-Mer','LFRF',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (50,'Lessay','LFOM',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (50,'Vauville','LFAU',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (51,'Écury-sur-Coole','LFQK',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (51,'Plivot','LFSW',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (51,'Prunay','LFQA',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (51,'Saint-Remy-sous-Broyes','LFFZ',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (51,'Vauclerc','LFSK',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (51,'Bussy-Lettrée','LFOK',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (51,'Marigny','LFYM',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (51,'Mourmelon-le-Grand','LFXM',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (51,'Reims','LFSR',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (52,'Chaumont','LFSY',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (52,'Semoutiers-Montsaon','LFJA',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (52,'Mussey-sur-Marne','LFFJ',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (52,'Rolampont','LFSU',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (52,'Saint-Dizier','LFSI',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (53,'Entrammes','LFOV',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (54,'Chambley-Bussières','LFJY',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (54,'Doncourt-lès-Conflans','LFGR',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (54,'Villette','LFGS',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (54,'Chanteheux, Croismare','LFQC',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (54,'Azelot','LFEX',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (54,'Tomblaine, Essey-lès-Nancy','LFSN',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (54,'Malzéville','LFEZ',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (54,'Pont-Saint-Vincent','LFSV',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (54,'Villerupt','LFAW',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (54,'Ochey, Thuilley-aux-Groseilles','LFSO',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (54,'Rosières-en-Haye','LFSL',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (55,'Les Hauts-de-Chée','LFEU',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (55,'Sommedieue','LFGW',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (55,'Étain','LFQE',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (55,'Marville','LFYK',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (56,'Plœmeur','LFRH',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (56,'Monterblanc','LFRV',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (56,'Guer','LFXQ',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (56,'Guiscriff','LFES',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (56,'Bangor','LFEA',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (56,'Loyat','LFRP',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (56,'Pontivy','LFED',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (56,'Quiberon','LFEQ',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (57,'Guéblange-lès-Dieuze','LFQZ',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (57,'Buhl-Lorraine','LFGT',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (57,'Frauenberg','LFGU',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (57,'Yutz','LFGV',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (57,'Bitche','LFXG',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (57,'Augny, Marly','LFSF',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (57,'Goin, Pagny-lès-Goin, Vigny, Liéhon et Silly-en-Saulnois','LFJL',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (57,'Bourscheid','LFQP',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (58,'Marzy','LFQG',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (58,'Clamecy','LFJC',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (58,'Cosne-Cours-sur-Loire','LFGH',1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (59,'Niergnies','LFYG',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (59,'Les Moëres','LFAK',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (59,'Lesquin','LFQQ',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (59,'Bondues','LFQO',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (59,'Vieux-Reng, Élesmes','LFQJ',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (59,'Lestrem, Calonne-sur-la-Lys, Merville','LFQT',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (59,'Prouvy, Rouvignies','LFAV',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (59,'Épinoy (62), Haynecourt (59)','LFQI',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (59,'Douai',NULL,1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (60,'Tillé','LFOB',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (60,'Le Plessis-Belleville','LFPP',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (60,'Compiègne','LFAD',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (60,'Creil','LFPC',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (61,'Saint-Sulpice-sur-Risle','LFOL',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (61,'Cerisé, Valframbert','LFOF',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (61,'Argentan','LFAJ',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (61,'Couterne','LFAO',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (61,'La Lande-Patry','LFOG',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (61,'Saint-Langis-lès-Mortagne','LFAX',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (62,'Roclincourt','LFQD',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (62,'Berck','LFAM',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (62,'Marck','LFAC',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (62,'Bénifontaine','LFQL',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (62,'Wizernes','LFQN',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (62,'Saint-Inglevert','LFIS',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (62,'Le Touquet-Paris-Plage','LFAT',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (62,'Vitry-en-Artois','LFQS',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (63,'Aulnat','LFLC',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (63,'Le Broc','LFHA',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (63,'Ambert','LFHT',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (64,'Biarritz, Anglet','LFBZ',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (64,'Itxassou','LFIX',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (64,'Lasclaveries','LFJV',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (64,'Herrère','LFCO',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (64,'Uzein','LFBP',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (65,'Laloubère','LFDT',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (65,'Castelnau-Magnoac','LFDQ',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (65,'Peyresourde','LFIP',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (65,'Ossun','LFBT',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (66,'Perpignan','LFMP',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (66,'La Llagonne','LFNQ',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (66,'Sainte-Léocadie','LFYS',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (67,'Haguenau','LFSH',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (67,'Sarre-Union','LFQU',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (67,'Strasbourg','LFGC',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (67,'Steinbourg','LFQY',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (67,'Entzheim','LFST',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (68,'Habsheim, Rixheim','LFGB',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (68,'Saint-Louis, Blotzheim','LFSB',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (68,'Saint-Louis, Blotzheim','LFSB',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (68,'Saint-Louis, Blotzheim','LFSB',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (68,'Colmar','LFGA',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (68,'Meyenheim','LFSC',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (69,'Colombier-Saugnieu','LFLL',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (69,'Corbas','LFHJ',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (69,'Frontenas','LFHV',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (69,'Saint-Jean-d''Ardières','LFHW',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (69,'Chassieu et Saint-Priest','LFLY',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (69,'Brindas','LFKL',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (70,'Broye-Aubigney-Montseugny','LFYH',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (70,'Gray','LFEV',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (70,'Malbouhans','LFYL',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (70,'Frotey-lès-Vesoul','LFQW',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (70,'Luxeuil-les-Bains','LFSX',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (71,'Autun','LFQF',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (71,'Champforgeuil','LFLH',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (71,'Saint-Yan','LFLN',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (71,'Charnay-lès-Mâcon','LFLM',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (71,'Pouilloux','LFGM',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (71,'Paray-le-Monial','LFGN',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (71,'Cuisery','LFFX',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (72,'Arnage','LFRM',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (72,'La Flèche, Thorée-les-Pins','LFAL',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (73,'Challes-les-Eaux, Barby','LFLE',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (73,'Bourget-du-Lac, La Motte-Servolex, Voglans et Viviers-du-Lac','LFLB',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (73,'Albertville','LFKA',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (73,'Les Allues','LFKX',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (73,'Saint-Bon-Tarentaise','LFLJ',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (73,'Sollières-Sardières','LFKD',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (73,'Saint-Rémy-de-Maurienne','LFKR',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (74,'Meythet','LFLP',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (74,'Annemasse, Ville-La-Grand, Vétraz-Monthoux, Cranves-Sales','LFLI',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (74,'Megève','LFHM',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (74,'Sallanches','LFHZ',1,1,1,1,1,1,1);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (75,'Paris','LFPI',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (76,'Saint-Aubin-sur-Scie','LFAB',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (76,'Gommerville','LFOY',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (76,'Boos','LFOP',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (76,'Eu','LFAE',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (76,'Le Havre, Octeville-sur-Mer','LFOH',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (76,'Saint-Sylvain, Saint-Riquier-ès-Plains, Vittefleur','LFOS',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (77,'Coulommiers','LFPK',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (77,'Chelles','LFPH',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (77,'Fontenay-Trésigny','LFPQ',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (77,'La Ferté-Gaucher','LFFG',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (77,'Lognes','LFPL',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (77,'Isles-lès-Villenoy','LFPE',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (77,'Montereau-sur-le-Jard, Réau','LFPM',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (77,'Épisy','LFPU',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (77,'Nangis','LFAI',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (78,'Thiverval-Grignon','LFPF',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (78,'Chavenay','LFPX',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (78,'Guyancourt','LFPR',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (78,'Les Mureaux, Verneuil-sur-Seine','LFXU',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (78,'Saint-Cyr-l''École','LFPZ',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (78,'Toussus-le-Noble','LFPN',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (78,'Vélizy-Villacoublay','LFPV',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (79,'Mauléon','LFJB',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (79,'Niort','LFBN',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (79,'Thouars','LFCT',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (80,'Abbeville','LFOI',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (80,'Amiens','LFAY',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (80,'Albert','LFAQ',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (80,'Montdidier','LFAR',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (80,'Péronne','LFAG',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (81,'Graulhet','LFCQ',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (81,'Le Séquestre','LFCI',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (81,'Castres','LFCK',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (81,'Gaillac','LFDG',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (82,'Castelsarrasin','LFCX',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (82,'Montauban','LFDB',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (83,'Le Castellet','LFMQ',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (83,'Cuers, Pierrefeu-du-Var','LFTF',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (83,'Fayence','LFMF',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (83,'Fréjus','LFTU',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (83,'Le Cannet-des-Maures','LFMC',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (83,'La Môle','LFTZ',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (83,'Grimaud',NULL,1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (83,'Hyères','LFTH',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (83,'Vinon-sur-Verdon','LFNF',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (84,'Avignon','LFMV',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (84,'Orange','LF51',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (84,'Carpentras','LFNH',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (84,'Orange','LFMO',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (84,'Pont-Saint-Esprit','LFND',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (84,'Saint-Christol','LFXI',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (84,'Visan','LFNV',1,1,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (85,'Beauvoir-sur-Mer','LF8561',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (85,'Fontenay-le-Comte','LFFK',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (85,'L''Île-d''Yeu','LFEY',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (85,'Saint-Georges-de-Montaigu','LFFW',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (85,'La Roche-sur-Yon','LFRI',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (85,'Les Sables-d''Olonne','LFOO',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (86,'Châtellerault','LFCA',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (86,'Chauvigny','LFDW',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (86,'Brux','LFDV',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (86,'Loudun','LFDL',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (86,'Biard','LFBI',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (87,'Limoges','LFBL',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (87,'Saint-Junien','LFBJ',1,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (88,'Damblain','LFYD',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (88,'Dogneville','LFSE',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (88,'Juvaincourt','LFSG',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (88,'Neufchâteau','LFFT',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (88,'Remomeix','LFGY',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (88,'Vittel','LFSZ',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (89,'Jaulges, Chéu','LFGP',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (89,'Joigny','LFGK',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (89,'Pont-sur-Yonne','LFGO',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (89,'Branches, Charbuy, Appoigny','LFLA',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (89,'Avallon','LFGE',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (90,'Chaux','LFGG',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (90,'Fontaine (Territoire de Belfort)','LFSQ',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (91,'Buno-Bonnevaux','LFFB',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (91,'Guillerval','LFOX',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (91,'Brétigny-sur-Orge','LFPY',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (91,'La Ferté-Alais','LFFQ',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES ('93, 95','Le Bourget...','LFPB',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES ('91, 94','Paray-Vieille-Poste, Orly...','LFPO',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES ('77, 93, 95','Roissy, Tremblay, Mitry','LFPG',1,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (95,'Bernes-sur-Oise, Bruyères-sur-Oise','LFPA',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (95,'Moisselles','LFFE',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (95,'Chérence','LFFC',1,NULL,1,1,1,NULL,NULL);
INSERT INTO "Liste_des_Aérodromes_en_France" VALUES (95,'Cormeilles-en-Vexin','LFPT',1,NULL,1,1,1,NULL,NULL);
COMMIT;
